# Einsum Examples

### Matrix Multiplication

In [3]:
import numpy as np

A = np.random.rand(3, 5)
B = np.random.rand(5, 2)

M = np.einsum('ik,kj->ij', A, B)
M

array([[1.37652385, 0.59341851],
       [1.63513343, 0.85959019],
       [1.62210018, 1.1943265 ]])

### Outer Product

In [12]:
a = np.random.rand(5)
b = np.random.rand(3)

outer = np.einsum('i,j->ij', a, b)
outer

array([[0.26726309, 0.02960492, 0.28510318],
       [0.70357997, 0.07793604, 0.75054465],
       [0.37360195, 0.04138415, 0.39854026],
       [0.04468744, 0.00495006, 0.04767037],
       [0.23909349, 0.02648455, 0.25505322]])

### Create a Sample Matrix

In [14]:
x = np.random.rand(2, 3)
x

array([[0.46616855, 0.50780734, 0.16815892],
       [0.90908244, 0.66653667, 0.19140193]])

### Transpose

In [15]:
np.einsum('ij->ji', x)

array([[0.46616855, 0.90908244],
       [0.50780734, 0.66653667],
       [0.16815892, 0.19140193]])

### Sum of All Elements

In [16]:
np.einsum('ij->', x)

np.float64(2.90915584666634)

### Column-wise Sum

In [17]:
np.einsum('ij->j', x)

array([1.37525098, 1.17434401, 0.35956085])

### Matrix Multiplication with a Transposed Operand

In [18]:
v = np.random.rand(1, 3)
np.einsum('ij, kj->ik', x, v)

array([[0.79218478],
       [1.26122738]])

### Vector Dot Product

In [20]:
np.einsum('i,i->', x[0], x[0])

np.float64(0.5034588353740747)

### Frobenius Inner Product

In [21]:
np.einsum('ij,ij->', x, x)

np.float64(1.810795544593008)

### Element-wise (Hadamard) Product

In [22]:
np.einsum('ij,ij->ij', x, x)

array([[0.21731311, 0.2578683 , 0.02827742],
       [0.82643088, 0.44427113, 0.0366347 ]])

### Batch Matrix Multiplication

In [23]:
a = np.random.rand(3, 2, 5)
b = np.random.rand(3, 5, 3)

np.einsum('ijk,ikl->ijl', a, b)

array([[[1.03021459, 1.60308258, 1.68940723],
        [0.80832373, 1.3514413 , 1.71955367]],

       [[1.76822112, 1.28937539, 1.83783372],
        [2.01771815, 1.3609514 , 1.51047796]],

       [[1.96491035, 1.2509101 , 1.23083706],
        [1.89593947, 1.18027181, 1.26575893]]])

### Diagonal Extraction

In [26]:
A = np.random.rand(3, 3)
print(A)
np.einsum("ii->i", A)

[[0.32368999 0.94912939 0.76109305]
 [0.04367635 0.24500532 0.3457772 ]
 [0.99804932 0.26325239 0.21059473]]


array([0.32368999, 0.24500532, 0.21059473])